version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    depends_on:
      - postgres
    volumes:
      - ./web:/usr/src/app
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app --reload

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static
    volumes_from:
      - web
    depends_on:
      - web

  # data:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     # - /var/lib/postgresql
  #     - ./postgresql
  #   command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      # - ./postgresql:/var/lib/postgresql
      - data_db:/var/lib/postgresql/data
      # - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data_db:
    external: true
      